package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strings"
	"sync"
	"time"
)

const (
	defaultServiceListURL = "https://servicereference.us-east-1.amazonaws.com/v1/service-list.json"
	serviceReferenceHost  = "servicereference.us-east-1.amazonaws.com"
	downloadWorkers       = 16
)

type serviceListEntry struct {
	Service string `json:"service"`
	URL     string `json:"url"`
}

type serviceReference struct {
	Name       string      `json:"Name"`
	Operations []operation `json:"Operations"`
}

type operation struct {
	Name              string             `json:"Name"`
	AuthorizedActions []authorizedAction `json:"AuthorizedActions"`
	SDK               []sdkClient        `json:"SDK"`
}

type authorizedAction struct {
	Name    string `json:"Name"`
	Service string `json:"Service"`
}

type sdkClient struct {
	Name string `json:"Name"`
}

type serviceResult struct {
	entry     serviceListEntry
	reference serviceReference
	err       error
}

func main() {
	output := flag.String("out", "core/policy/iam_mappings.tsv", "output mapping file")
	serviceListURL := flag.String("service-list", defaultServiceListURL, "AWS service reference index")
	flag.Parse()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	client := &http.Client{Timeout: 30 * time.Second}
	var services []serviceListEntry
	if err := fetchJSON(ctx, client, *serviceListURL, &services); err != nil {
		log.Fatalf("download service list: %v", err)
	}
	if len(services) == 0 {
		log.Fatal("download service list: no services returned")
	}
	sort.Slice(services, func(i, j int) bool {
		return services[i].Service < services[j].Service
	})

	results := downloadServices(ctx, client, services)
	mappings := make(map[string]map[string]struct{})
	processed := 0
	for result := range results {
		if result.err != nil {
			log.Fatalf("download %s: %v", result.entry.Service, result.err)
		}
		processed++
		addServiceMappings(mappings, result.entry, result.reference)
	}

	var data bytes.Buffer
	fmt.Fprintln(&data, "# Code generated by scripts/generate_iam_mappings.go; DO NOT EDIT.")
	fmt.Fprintf(&data, "# Source: %s\n", *serviceListURL)
	fmt.Fprintf(&data, "# Services: %d\n", processed)

	keys := make([]string, 0, len(mappings))
	for key := range mappings {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		actions := make([]string, 0, len(mappings[key]))
		for action := range mappings[key] {
			actions = append(actions, action)
		}
		sort.Strings(actions)
		fmt.Fprintf(&data, "%s\t%s\n", key, strings.Join(actions, ","))
	}

	if err := os.WriteFile(*output, data.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", *output, err)
	}
	fmt.Printf("wrote %s with %d mappings from %d services\n", *output, len(keys), processed)
}

func downloadServices(ctx context.Context, client *http.Client, services []serviceListEntry) <-chan serviceResult {
	jobs := make(chan serviceListEntry)
	results := make(chan serviceResult)

	workers := min(downloadWorkers, len(services))
	var wg sync.WaitGroup
	wg.Add(workers)
	for range workers {
		go func() {
			defer wg.Done()
			for entry := range jobs {
				var reference serviceReference
				err := fetchJSON(ctx, client, entry.URL, &reference)
				results <- serviceResult{entry: entry, reference: reference, err: err}
			}
		}()
	}

	go func() {
		for _, service := range services {
			jobs <- service
		}
		close(jobs)
		wg.Wait()
		close(results)
	}()

	return results
}

func addServiceMappings(mappings map[string]map[string]struct{}, entry serviceListEntry, reference serviceReference) {
	defaultSources := []string{entry.Service, reference.Name}
	for _, operation := range reference.Operations {
		if operation.Name == "" || len(operation.AuthorizedActions) == 0 {
			continue
		}

		sources := make(map[string]struct{})
		for _, source := range defaultSources {
			if source = normalizeSource(source); source != "" {
				sources[source] = struct{}{}
			}
		}
		for _, sdk := range operation.SDK {
			if source := normalizeSource(sdk.Name); source != "" {
				sources[source] = struct{}{}
			}
		}

		actions := make([]string, 0, len(operation.AuthorizedActions))
		for _, action := range operation.AuthorizedActions {
			service := strings.ToLower(strings.TrimSpace(action.Service))
			name := strings.TrimSpace(action.Name)
			if service == "" || name == "" {
				continue
			}
			actions = append(actions, service+":"+name)
		}
		if len(actions) == 0 {
			continue
		}
		for source := range sources {
			key := source + ":" + operation.Name
			if mappings[key] == nil {
				mappings[key] = make(map[string]struct{})
			}
			for _, action := range actions {
				mappings[key][action] = struct{}{}
			}
		}
	}
}

func normalizeSource(source string) string {
	source = strings.ToLower(strings.TrimSpace(source))
	return strings.TrimSuffix(source, ".amazonaws.com")
}

func fetchJSON(ctx context.Context, client *http.Client, rawURL string, target any) error {
	parsed, err := url.Parse(rawURL)
	if err != nil {
		return err
	}
	if parsed.Scheme != "https" || parsed.Host != serviceReferenceHost {
		return fmt.Errorf("unexpected service reference URL %q", rawURL)
	}

	var lastErr error
	for attempt := range 3 {
		if attempt > 0 {
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-time.After(time.Duration(attempt) * 250 * time.Millisecond):
			}
		}

		request, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
		if err != nil {
			return err
		}
		request.Header.Set("User-Agent", "trailtool-iam-mapping-generator")
		response, err := client.Do(request)
		if err != nil {
			lastErr = err
			continue
		}
		body, readErr := io.ReadAll(io.LimitReader(response.Body, 64<<20))
		closeErr := response.Body.Close()
		if readErr != nil {
			lastErr = readErr
			continue
		}
		if closeErr != nil {
			lastErr = closeErr
			continue
		}
		if response.StatusCode != http.StatusOK {
			lastErr = fmt.Errorf("GET %s: %s", rawURL, response.Status)
			if response.StatusCode < http.StatusInternalServerError {
				return lastErr
			}
			continue
		}
		if err := json.Unmarshal(body, target); err != nil {
			return fmt.Errorf("decode %s: %w", rawURL, err)
		}
		return nil
	}
	return lastErr
}
